# Generated by Django 5.2.6 on 2025-10-02 10:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                (
                    'age',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1, 'Age can not be less than 1')]
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('CREATE', 'Create'),
                            ('READ_ALL', 'Read All'),
                            ('UPDATE', 'Update'),
                            ('DELETE', 'Delete'),
                            ('ALL', 'All'),
                        ],
                        max_length=10,
                    ),
                ),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleBinding',
            fields=[
                ('role_binding_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                (
                    'role_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userrole'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserRolePermissionBinding',
            fields=[
                ('permission_binding_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                (
                    'permission_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='user_management.userrolepermission'
                    ),
                ),
                (
                    'role_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userrole'),
                ),
            ],
        ),
    ]
