# Generated by Django 5.2.6 on 2025-10-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrolepermissionbinding',
            constraint=models.UniqueConstraint(fields=('role_id', 'permission_id'), name='unique_permission_per_role'),
        ),
    ]
