# Generated by Django 5.2.6 on 2025-10-03 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userrolepermissionbinding_unique_permission_per_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolebinding',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
