# Generated by Django 5.2.6 on 2025-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_userrolebinding_user_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrolebinding',
            constraint=models.UniqueConstraint(fields=('user_id', 'role_id'), name='unique_role_per_user'),
        ),
    ]
