# Generated by Django 5.2.6 on 2025-10-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_userrolebinding_unique_role_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='userrolebinding',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='userrolepermission',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='userrolepermissionbinding',
            options={'ordering': ['-created_date']},
        ),
    ]
