# Generated by Django 5.2.6 on 2025-10-03 07:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('AVAILABLE', 'Available'),
                            ('RENTED', 'Rented'),
                            ('OUT_OF_SERVICE', 'Out Of Service'),
                        ],
                        default='AVAILABLE',
                        max_length=20,
                    ),
                ),
                ('author', models.CharField(max_length=255)),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_detail', models.TextField()),
                ('is_recommended', models.BooleanField(default=False)),
                (
                    'book_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.book'),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RentHistoryModel',
            fields=[
                ('rent_id', models.AutoField(primary_key=True, serialize=False)),
                ('rented_date', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')],
                        default='IN_PROGRESS',
                        max_length=20,
                    ),
                ),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                (
                    'late_return_fee',
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0, 'Late penalty fee can not be negative')
                        ],
                    ),
                ),
                (
                    'book_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.book'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='rent_user_id',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BookTagBinding',
            fields=[
                ('book_tag_binding_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                (
                    'book_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.book'),
                ),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.tag')),
            ],
        ),
    ]
