# Generated by Django 5.2.6 on 2025-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booktagbinding',
            constraint=models.UniqueConstraint(fields=('book_id', 'tag_id'), name='unique_tag_per_book_record'),
        ),
    ]
