# Generated by Django 5.2.6 on 2025-10-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0002_booktagbinding_unique_tag_per_book_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
