# Generated by Django 5.2.6 on 2025-10-07 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0005_alter_book_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='booktagbinding',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='renthistorymodel',
            options={'ordering': ['-rented_date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='bookreview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
