# Generated by Django 5.2.6 on 2025-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0006_alter_book_options_alter_bookreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthistorymodel',
            name='status',
            field=models.CharField(
                choices=[
                    ('IN_PROGRESS', 'In Progress'),
                    ('COMPLETED', 'Completed'),
                    ('OVERDUE', 'Overdue'),
                    ('UNPAID', 'Unpaid'),
                ],
                default='IN_PROGRESS',
                max_length=20,
            ),
        ),
    ]
